### ISSUE TITLE
Followers sometimes stop following if too far out of date

### ISSUE THREAD

**Issue by weggert** [Comcast/sirius#108]
We are seeing an issue where a following server stops getting updates from the cluster it is following.  It seems to happen when the following server gets a few days behind (due to limited connectivity or due to replacing the WAL file with older data).

Once the following server stops following, it will not start following again.  The only known fix is to replace the WAL file with a more up-to-date WAL file and restart.

Our working theory is that compaction clears out an entry from the WAL on primary server, and the follower then can't catch up because of that.

I can provide example WAL files that exhibit the issue (both primary server and follow WAL files).  However they are quite large.

**Comment by comcast-jonm** [comment]
Hi @weggert, thanks for letting us know. At first blush, your hypothesis seems plausible--we'll investigate. I suspect that you're running into a case where the follower is asking for a window of updates, but they've ALL been compacted away everywhere else. We might need to add a catchup protocol message that differentiates the current "I have no updates in that window" from "I have no updates in that window, but I know of some later ones." I don't think we need you to provide the example WAL files for now--let's try to reproduce without them.

In the meantime, glad there is an operational workaround (if inconvenient).

**Comment by clinedome-work** [comment]
Thanks for the report @weggert. I dug into this yesterday afternoon and uncovered the issue. While we do have the kind of message @comcast-jonm suggested (an EmptySubrange message), and we were marking it as a successful request (thus increasing the request window size), it was not updating the nextSeq on the follower side. I suspect that the issue was often masked by the fact that as the request window size grew, there would eventually be *some* event within the range that had not been compacted away. If there were no remaining events within the next `MAX_WINDOW_SIZE` sequence numbers, however, it would get stuck. I've got a quick PR upcoming that addresses this issue.

**Comment by clinedome-work** [comment]
See #109

**Comment by clinedome-work** [comment]
This was addressed by #109 (and released in #110). @weggert can you confirm that the 1.2.4 release fixes your issue? If so, are you comfortable with us closing this?

**Comment by joercampbell** [comment]
Confirmed Pete - we deployed to a Dev environment that previously was stuck not following and it immediately caught up.

**Comment by weggert** [comment]
Confirmed that the 1.2.4 release fixed the issue.  The 'stuck' followers became unstuck with this change.

**Comment by weggert** [comment]
Thank you for the quick resolution and release.  :-) It is going out to our production environment today.
